# Generated by Django 5.2.13 on 2026-05-05 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("status_changed", "Status Changed"),
                            ("activated", "Activated"),
                            ("archived", "Archived"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("converted", "Converted"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("system", "System"),
                        ],
                        help_text="Durchgeführte Aktion",
                        max_length=80,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Typ der betroffenen Entität (z.B. app_label.ModelName)",
                        max_length=120,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True,
                        help_text="ID der betroffenen Entität",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "entity_repr",
                    models.CharField(
                        blank=True,
                        help_text="Lesbare Darstellung der betroffenen Entität",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Zusätzliche Nachricht oder Kontext"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Änderungen: {"field": {"old": value, "new": value}}',
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Zusätzliche Metadaten"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP-Adresse der Anfrage", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User-Agent der Anfrage"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Zeitstempel des Audit-Eintrags"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Benutzer, der die Aktion durchgeführt hat",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_log_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Log Entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action"], name="auditlog_au_action_d99068_idx"
                    ),
                    models.Index(
                        fields=["entity_type"], name="auditlog_au_entity__255ff4_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="auditlog_au_created_824869_idx"
                    ),
                ],
            },
        ),
    ]
