# Generated by Django 5.2.13 on 2026-05-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlogentry",
            name="user_agent",
            field=models.TextField(
                blank=True, help_text="User-Agent der Anfrage", null=True
            ),
        ),
    ]
