# Generated by Django 5.2.13 on 2026-05-05 10:07

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="checkout_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Snapshot of checkout context (customer_group, currency, item_count, amounts)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Snapshot of payment method (no secrets)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Final shipping amount from checkout",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Snapshot of shipping method (no secrets)",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("shipping_amount__gte", 0)),
                name="orders_order_shipping_amount_non_negative",
            ),
        ),
    ]
