# Generated by Django 5.2.13 on 2026-05-05 04:05

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name der Versandzone (z.B. Deutschland, EU, International)",
                        max_length=120,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Eindeutiger Code der Zone (z.B. DE, EU, INT)",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "countries",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=3),
                        blank=True,
                        default=list,
                        help_text='ISO-Ländercodes (z.B. ["DE", "AT", "CH"])',
                        size=None,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Zone ist aktiv und wird für Versandberechnung berücksichtigt",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Sortierreihenfolge"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shipping Zone",
                "verbose_name_plural": "Shipping Zones",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(fields=["code"], name="shipping_sh_code_ec4c56_idx"),
                    models.Index(
                        fields=["is_active"], name="shipping_sh_is_acti_f5d5a3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name der Versandmethode (z.B. Standardversand, Expressversand)",
                        max_length=120,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Eindeutiger Code (z.B. standard_de, express_de)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "customer_group",
                    models.CharField(
                        choices=[
                            ("all", "All (B2C and B2B)"),
                            ("b2c", "B2C"),
                            ("b2b", "B2B"),
                        ],
                        default="all",
                        help_text="Kundengruppe: all, b2c oder b2b",
                        max_length=10,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Basis-Versandkosten",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", help_text="Währung (ISO 4217 Code)", max_length=3
                    ),
                ),
                (
                    "estimated_min_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimale geschätzte Liefertage",
                        null=True,
                    ),
                ),
                (
                    "estimated_max_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximale geschätzte Liefertage",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Methode ist aktiv"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Sortierreihenfolge"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "zone",
                    models.ForeignKey(
                        help_text="Versandzone dieser Methode",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipping_methods",
                        to="shipping.shippingzone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Method",
                "verbose_name_plural": "Shipping Methods",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ShippingRateSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_code",
                    models.CharField(
                        help_text="Code der Versandmethode (Snapshot, unveränderlich)",
                        max_length=64,
                    ),
                ),
                (
                    "method_name",
                    models.CharField(
                        help_text="Name der Versandmethode (Snapshot, unveränderlich)",
                        max_length=120,
                    ),
                ),
                (
                    "zone_code",
                    models.CharField(
                        help_text="Code der Versandzone (Snapshot, unveränderlich)",
                        max_length=32,
                    ),
                ),
                (
                    "zone_name",
                    models.CharField(
                        help_text="Name der Versandzone (Snapshot, unveränderlich)",
                        max_length=120,
                    ),
                ),
                (
                    "customer_group",
                    models.CharField(
                        choices=[("b2c", "B2C"), ("b2b", "B2B")],
                        help_text="Kundengruppe bei Snapshot-Erstellung",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Versandkosten-Betrag des Snapshots",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="EUR", help_text="Währung", max_length=3),
                ),
                (
                    "estimated_min_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimale geschätzte Liefertage (Snapshot)",
                        null=True,
                    ),
                ),
                (
                    "estimated_max_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximale geschätzte Liefertage (Snapshot)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "method",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referenz zur Versandmethode (kann gelöscht werden)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rate_snapshots",
                        to="shipping.shippingmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Rate Snapshot",
                "verbose_name_plural": "Shipping Rate Snapshots",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["method_code"], name="shipping_sh_method__41aad2_idx"
                    ),
                    models.Index(
                        fields=["customer_group"], name="shipping_sh_custome_070b87_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="shipping_sh_created_e2e76e_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)),
                        name="shipping_snapshot_amount_non_negative",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="shippingmethod",
            index=models.Index(
                fields=["zone", "is_active"], name="shipping_sh_zone_id_c68dcb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shippingmethod",
            index=models.Index(fields=["code"], name="shipping_sh_code_59083d_idx"),
        ),
        migrations.AddIndex(
            model_name="shippingmethod",
            index=models.Index(
                fields=["customer_group"], name="shipping_sh_custome_aa8dd1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingmethod",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_price__gte", 0)),
                name="shipping_method_base_price_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingmethod",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("estimated_max_days__isnull", True),
                    ("estimated_min_days__isnull", True),
                    ("estimated_max_days__gte", models.F("estimated_min_days")),
                    _connector="OR",
                ),
                name="shipping_method_estimated_days_valid",
            ),
        ),
    ]
