# Generated by Django 5.2.13 on 2026-05-05 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("imprint", "Impressum"),
                            ("privacy_policy", "Datenschutzrichtlinie"),
                            ("terms_b2c", "AGB B2C"),
                            ("terms_b2b", "AGB B2B"),
                            ("withdrawal_b2c", "Widerrufsrecht B2C"),
                            ("shipping_info", "Versandinformation"),
                            ("payment_info", "Zahlungsinformation"),
                            ("cookie_policy", "Cookie-Richtlinie"),
                            ("other", "Sonstiges"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "target_group",
                    models.CharField(
                        choices=[("all", "Alle"), ("b2c", "B2C"), ("b2b", "B2B")],
                        default="all",
                        max_length=16,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_required", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rechtsdokument",
                "verbose_name_plural": "Rechtsdokumente",
                "ordering": ["document_type", "target_group", "title"],
            },
        ),
        migrations.CreateModel(
            name="LegalDocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("active", "Aktiv"),
                            ("archived", "Archiviert"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("summary", models.TextField(blank=True, null=True)),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legal_versions_activated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legal_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="legal.legaldocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rechtsdokument-Version",
                "verbose_name_plural": "Rechtsdokument-Versionen",
                "ordering": ["document", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "version"), name="unique_document_version"
                    )
                ],
            },
        ),
    ]
