# Generated by Django 5.2.13 on 2026-05-05 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("necessary", "Notwendig"),
                            ("analytics", "Analytik"),
                            ("marketing", "Marketing"),
                            ("preferences", "Einstellungen"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="necessary-Kategorie sollte required sein",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Consent-Kategorie",
                "verbose_name_plural": "Consent-Kategorien",
                "ordering": ["sort_order", "key"],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=80, null=True
                    ),
                ),
                ("granted", models.BooleanField()),
                ("consent_version", models.CharField(default="v1", max_length=32)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("banner", "Banner"),
                            ("account", "Account"),
                            ("admin", "Admin"),
                            ("system", "System"),
                        ],
                        default="banner",
                        max_length=16,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_records",
                        to="consent.consentcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent-Record",
                "verbose_name_plural": "Consent-Records",
                "ordering": ["-created_at"],
            },
        ),
    ]
