# Generated by Django 5.2.13 on 2026-05-05 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0001_initial"),
        ("orders", "0001_initial"),
        ("payments", "0001_initial"),
        ("shipping", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("validated", "Validated"),
                            ("order_created", "Order Created"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="started",
                        max_length=32,
                    ),
                ),
                (
                    "customer_group",
                    models.CharField(
                        choices=[("b2c", "B2C"), ("b2b", "B2B")],
                        default="b2c",
                        max_length=10,
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "shipping_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot der Versandmethode (keine Secrets)",
                    ),
                ),
                (
                    "shipping_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "payment_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot der Zahlungsmethode (keine Secrets)",
                    ),
                ),
                (
                    "cart_subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "order_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("item_count", models.PositiveIntegerField(default=0)),
                (
                    "legal_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot der Rechtsvereinbarungen",
                    ),
                ),
                (
                    "consent_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot der Zustimmungen (Consent)",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("order_created_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkout_sessions",
                        to="cart.cart",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkout_session",
                        to="orders.order",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkout_sessions",
                        to="payments.paymentmethod",
                    ),
                ),
                (
                    "shipping_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkout_sessions",
                        to="shipping.shippingmethod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkout_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckoutEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("validated", "Validated"),
                            ("shipping_selected", "Shipping Selected"),
                            ("payment_selected", "Payment Selected"),
                            ("legal_checked", "Legal Checked"),
                            ("consent_checked", "Consent Checked"),
                            ("order_created", "Order Created"),
                            ("cancelled", "Cancelled"),
                            ("error", "Error"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Zusätzliche Daten (keine Secrets)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checkout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="checkout.checkoutsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="checkoutsession",
            index=models.Index(
                fields=["status", "-updated_at"], name="checkout_ch_status_ec02e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutsession",
            index=models.Index(
                fields=["user", "-created_at"], name="checkout_ch_user_id_e6e24b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutsession",
            index=models.Index(fields=["cart"], name="checkout_ch_cart_id_1a4d51_idx"),
        ),
        migrations.AddConstraint(
            model_name="checkoutsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("shipping_amount__gte", 0)),
                name="checkout_shipping_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="checkoutsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("cart_subtotal__gte", 0)),
                name="checkout_cart_subtotal_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="checkoutsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("order_total__gte", 0)),
                name="checkout_order_total_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="checkoutsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("item_count__gte", 0)),
                name="checkout_item_count_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutevent",
            index=models.Index(
                fields=["checkout", "-created_at"],
                name="checkout_ch_checkou_f4f0a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutevent",
            index=models.Index(
                fields=["event_type"], name="checkout_ch_event_t_d0034e_idx"
            ),
        ),
    ]
